### ISSUE TITLE
Pulls up the app, but it doesn't work

### ISSUE THREAD

**Issue by languagemaniac** [jaypyles/Scraperr#20]
Hi, sorry I might have spoken too soon in my previous issue. The app is available at localhost:9000, however, it doesn't do anything.

I can write stuff in the url; however the letters "URL" don't go away, the submit button doesn't work; the login button doesn't work, the settings button doesn't work either; I can't check the boxes...

**Comment by jaypyles** [comment]
Are you using an older browser, I know I have had issues with some apps built in newer version of Angular not working on older browsers. This could be the case, since I am developing using the newest version of Next.js.

**Comment by languagemaniac** [comment]
I'm using the latest brave browser. Also downloaded the latest chrome just in case. The only difference is that in chrome the submit button is blue, and in brave is gray.

this is my current docker compose as I understood from your previous paste, just in case I understood wrong.

```
version: '3.9' 

services:
  scraperr:
    image: jpyles0524/scraperr:latest
    init: true
    build:
      context: ./
    container_name: scraperr
    ports:
      - 9000:8000
    env_file:
      - ./.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web

networks:
  web:
  ```
  
  Or maybe I should have kept the mongo image in there? I also tried with mongo in there (don't know what I'm doing)
  
  ```
  version: '3.9' 
  
services:
   scraperr:
    image: jpyles0524/scraperr:latest
    init: true
    build:
      context: ./
    container_name: scraperr
    ports:
      - 9000:8000
    env_file:
      - ./.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web

  mongo:
    container_name: webscrape-mongo
    image: mongo:4.4.7
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - web

networks:
  web:
  ```
  
  But the result is the same

**Comment by jaypyles** [comment]
> I'm using the latest brave browser. Also downloaded the latest chrome just in case. The only difference is that in chrome the submit button is blue, and in brave is gray.
> 
> this is my current docker compose as I understood from your previous paste, just in case I understood wrong.
> 
> ```
> version: '3.9' 
> 
> services:
>   scraperr:
>     image: jpyles0524/scraperr:latest
>     init: true
>     build:
>       context: ./
>     container_name: scraperr
>     ports:
>       - 9000:8000
>     env_file:
>       - ./.env
>     volumes:
>       - /var/run/docker.sock:/var/run/docker.sock
>     networks:
>       - web
> 
> networks:
>   web:
> ```
> 
> Or maybe I should have kept the mongo image in there? I also tried with mongo in there (don't know what I'm doing)
> 
> ```
> version: '3.9' 
> 
> services:
>  scraperr:
>   image: jpyles0524/scraperr:latest
>   init: true
>   build:
>     context: ./
>   container_name: scraperr
>   ports:
>     - 9000:8000
>   env_file:
>     - ./.env
>   volumes:
>     - /var/run/docker.sock:/var/run/docker.sock
>   networks:
>     - web
> 
> mongo:
>   container_name: webscrape-mongo
>   image: mongo:4.4.7
>   restart: always
>   environment:
>     MONGO_INITDB_ROOT_USERNAME: root
>     MONGO_INITDB_ROOT_PASSWORD: example
>   networks:
>     - web
> 
> networks:
> web:
> ```
> 
> But the result is the same

The app relies on mongodb, you need that. Try `make pull up`

**Comment by languagemaniac** [comment]
> The app relies on mongodb, you need that. Try `make pull up`

Trying with the second docker-compose I pasted that includes mongodb; tried make pull up but the result is the same

**Comment by languagemaniac** [comment]
if it helps somehow, here are scraperr logs

```
2024-07-22 21:52:36,801 CRIT Supervisor is running as root.  Privileges were not dropped because no us
 you can set user=root in the config file to avoid this message.
2024-07-22 21:52:36,804 INFO supervisord started with pid 7
2024-07-22 21:52:37,806 INFO spawned: 'api' with pid 8
2024-07-22 21:52:37,809 INFO spawned: 'worker' with pid 9
2024-07-22 21:52:38,810 INFO success: api entered RUNNING state, process has stayed up for > than 1 se
2024-07-22 21:52:38,811 INFO success: worker entered RUNNING state, process has stayed up for > than 1
INFO:     Will watch for changes in these directories: ['/project']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [16] using WatchFiles
INFO:__main__:Starting job worker...
INFO:     Started server process [19]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
[lots of Invalid HTTP request received.]
INFO:     172.22.0.1:60386 - "GET / HTTP/1.1" 200 OK
[lots of Invalid HTTP request received.]
```

mongo looks fine

**Comment by jaypyles** [comment]
> if it helps somehow, here are scraperr logs
> 
> ```
> 2024-07-22 21:52:36,801 CRIT Supervisor is running as root.  Privileges were not dropped because no us
>  you can set user=root in the config file to avoid this message.
> 2024-07-22 21:52:36,804 INFO supervisord started with pid 7
> 2024-07-22 21:52:37,806 INFO spawned: 'api' with pid 8
> 2024-07-22 21:52:37,809 INFO spawned: 'worker' with pid 9
> 2024-07-22 21:52:38,810 INFO success: api entered RUNNING state, process has stayed up for > than 1 se
> 2024-07-22 21:52:38,811 INFO success: worker entered RUNNING state, process has stayed up for > than 1
> INFO:     Will watch for changes in these directories: ['/project']
> INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
> INFO:     Started reloader process [16] using WatchFiles
> INFO:__main__:Starting job worker...
> INFO:     Started server process [19]
> INFO:     Waiting for application startup.
> INFO:     Application startup complete.
> WARNING:  Invalid HTTP request received.
> WARNING:  Invalid HTTP request received.
> [lots of Invalid HTTP request received.]
> INFO:     172.22.0.1:60386 - "GET / HTTP/1.1" 200 OK
> [lots of Invalid HTTP request received.]
> ```
> 
> mongo looks fine

Are you accessing the site at `https://localhost:9000` or `http://localhost:9000`, you are not using secure right now, as you haven't provided an SSL certificate, so you should be accessing it at the second one.

**Comment by languagemaniac** [comment]
> Are you accessing the site at `https://localhost:9000` or `http://localhost:9000`, you are not using secure right now, as you haven't provided an SSL certificate, so you should be accessing it at the second one.

Yes i am using http not https

**Comment by jaypyles** [comment]
> > Are you accessing the site at `https://localhost:9000` or `http://localhost:9000`, you are not using secure right now, as you haven't provided an SSL certificate, so you should be accessing it at the second one.
> 
> Yes I am using http not https
> 
> Just in case it matters, I'm running this in a home server and accessing via the server's local ip with another computer in the same network.

Okay, letting you know I have been able to reproduce the issue this way. I'll reply once I have fixed it.

**Comment by languagemaniac** [comment]
> > > Are you accessing the site at `https://localhost:9000` or `http://localhost:9000`, you are not using secure right now, as you haven't provided an SSL certificate, so you should be accessing it at the second one.
> > 
> > 
> > Yes I am using http not https
> > Just in case it matters, I'm running this in a home server and accessing via the server's local ip with another computer in the same network.
> 
> Okay, letting you know I have been able to reproduce the issue this way. I'll reply once I have fixed it.

Great, i found a real issue and not just an issue on my side :'') could it have anything to do with the website not working the way it should? Or this is still an issue on my side

**Comment by jaypyles** [comment]
> > > > Are you accessing the site at `https://localhost:9000` or `http://localhost:9000`, you are not using secure right now, as you haven't provided an SSL certificate, so you should be accessing it at the second one.
> > > 
> > > 
> > > Yes I am using http not https
> > > Just in case it matters, I'm running this in a home server and accessing via the server's local ip with another computer in the same network.
> > 
> > 
> > Okay, letting you know I have been able to reproduce the issue this way. I'll reply once I have fixed it.
> 
> Great, i found a real issue and not just an issue on my side :'') could it have anything to do with the website not working the way it should? Or this is still an issue on my side

There was a line in the template document header for the app that was upgrading insecure requests to secure, I am not sure why it only happens when accessing the app remotely. I am pushing a change now that should fix it, i'll lyk once its fixed.

**Comment by jaypyles** [comment]
@languagemaniac change has been pushed. Try `make pull up` again and lmk if its working for you.

**Comment by languagemaniac** [comment]
> @languagemaniac change has been pushed. Try `make pull up` again and lmk if its working for you.

It's a bit late so i turned off my PC and tried on Android and it does work now, haven't tried scraping but the buttons do work.

My browsers are not in their latest version, so it didn't work on brave browser but it did work in Firefox so I'd say you fixed it right. Thanks! Will try scraping something soon

**Comment by languagemaniac** [comment]
Accessing the page with brave browser produces invalid http errors and the page doesn't work. Accessing with Firefox does work. I'll test this in PC tomorrow
